from time import sleep
from random import randint


BETTING_HOUSES_LINKS = {
    "Codere": "https://m.apuestas.codere.es/deportes/index.htm#/NearestLocalPage"
}


def random_sleep():
    sleep(randint(1, 4))


NAME_DICT = {'a coruña': 'coruña, a',
 'alcalá de henares': 'alcala de henares',
 'linea de la concepcion': 'linea de la concepcion, la',
 'la jonquera': 'jonquera, la',
 'línea de la concepcion': 'linea de la concepcion, la',
 'corvera': 'corera',
 'el escorial': 'escorial, el',
 'pozuelo de alarcón': 'pozuelo de alarcon',
 'san sebastián de los reyes': 'san sebastian de los reyes',
 'san martín de valdeiglesias': 'san martin de valdeiglesias',
 'alcorcón': 'alcorcon',
 'fernan nuñez': 'fernan-nuñez',
 'castellon': 'castello',
 'san agustin de guadalix': 'san agustin del guadalix',
 'velilla san antonio': 'velilla de san antonio',
 'almunia de doña godina': 'almunia de doña godina, la',
 'castellon de la plana': 'castello de la plana',
 'overa': 'vera',
 'móstoles': 'mostoles',
 'leganés': 'leganes',
 'los barrios': 'barrios, los',
 'córdoba': 'cordoba',
 'el molar': 'molar, el',
 'torre del campo': 'torredelcampo',
 'villaba-atarrabia': 'villava/atarrabia',
 'la rambla': 'rambla, la',
 'la solana': 'solana, la',
 'la carlota': 'carlota, la',
 'la vila joiosa/villajoyosa': 'villajoyosa/vila joiosa, la',
 'o carballiño': 'carballiño, o',
 'orense': 'ourense',
 'a estrada': 'estrada, a',
 'els poblets': 'poblets, els',
 'carballiño': 'carballiño, o',
 'vilamarín': 'vilamarin',
 'castelló de la plana': 'castello de la plana',
 'benaguacil': 'benaguasil',
 'donostia san sebastian': 'donostia/san sebastian',
 'quart de poblet_old': 'quart de poblet',
 'vitoria gasteiz': 'vitoria-gasteiz',
 'pontes de garcia rodriguez a': 'pontes de garcia rodriguez, as',
 'el burgo-burgelu': 'elburgo/burgelu',
 'gadalkao': 'galdakao',
 'valle de trapaga trapagaran': 'valle de trapaga-trapagaran',
 'lasarte oria': 'lasarte-oria',
 "l'hospitalet de llobregat": "hospitalet de llobregat, l'",
 'vilanova y la geltru': 'vilanova i la geltru',
 'renteria': 'errenteria',
 'alcacer': 'alcocer',
 'benirredrà': 'benirredra',
 'gernika lumo': 'gernika-lumo',
 'montcada': 'moncada',
 'as pontes de garcía rodríguez': 'pontes de garcia rodriguez, as',
 'alaquàs': 'alaquas',
 'rivas vaciamadrid': 'rivas-vaciamadrid',
 'cervera rio alhama': 'cervera del rio alhama',
 'ràfol de salem': 'rafol de salem',
 'bétera': 'betera',
 'puenteareas': 'ponteareas',
 'a mezquita': 'mezquita, a',
 'as pontes de garcia rodriguez': 'pontes de garcia rodriguez, as',
 "l'alcora": "alcora, l'",
 'socuéllamos': 'socuellamos',
 'la roda': 'roda, la',
 'buitrago de lozoya': 'buitrago del lozoya',
 'arteijo': 'arteixo',
 'tabernes blanques': 'tavernes blanques',
 'fuente maestre': 'fuente del maestre',
 'donostia-san sebastian': 'donostia/san sebastian',
 'legazpia': 'legazpi',
 'sta comba': 'santa comba',
 'a gudiña': 'gudiña, a',
 'igeldo': 'geldo',
 'torrejón de ardoz': 'torrejon de ardoz',
 'alcàsser': 'alcasser',
 'beniperrel': 'beniparrell',
 'monserrat': 'montserrat',
 'beriáin': 'beriain',
 'real de gandia': 'real de gandia, el',
 'llíria': 'lliria',
 'la mata': 'mata, la',
 'rábade': 'rabade',
 'vinaroz': 'vinaros',
 'benetússer': 'benetusser',
 'carballiño o': 'carballiño, o',
 'pastoriza': 'pastoriza, a',
 'olite': 'oliete',
 'artiziniega': 'artziniega',
 'pobla de vallbona': 'pobla de vallbona, la',
 'el verger': 'verger, el',
 'torrejón de la calzada': 'torrejon de la calzada',
 'la nucia': 'nucia, la',
 'castelló de rugat': 'castello de rugat',
 'cehegín': 'cehegin',
 'los alcázares': 'alcazares, los',
 'castro urdiales': 'castro-urdiales',
 'casas ibañez': 'casas-ibañez',
 'el ejido': 'ejido, el',
 'las pedroñeras': 'pedroñeras, las',
 'san martín de la vega': 'san martin de la vega',
 'puebla de montalban': 'puebla de montalban, la',
 'ansoain': 'andoain',
 'el algarrobo': 'algarrobo',
 'amorebieta-echano': 'amorebieta-etxano',
 'corcubión': 'corcubion',
 'málaga': 'malaga',
 'la union': 'union, la',
 'crevillente': 'crevillent',
 'las torres de cotillas': 'torres de cotillas, las',
 'donostia- san sebastian': 'donostia/san sebastian'}